name = "MySciMLProject"
uuid = "a1b2c3d4-e5f6-7890-1234-567890abcdef"
authors = ["Toi"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40ce-9e80-0db7422f6c4a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-afa7-412f9b7430c2"
OptimizationOptimisers = "42dfb2eb-053b-4277-8d08-1a524024b4e1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLSensitivity = "1ed8b502-d754-44cc-9e76-0d923769c218"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Printf = "de0858da-6303-5e67-8744-51ed9e6a7471"
